version: "3.5"
services:
  disk-exporter:
    image: exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: disk-info
    ports:
      - "9000:9000"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - wx
networks:
  wx:
    external: true