version: "3.5"
services:
  disk-exporter:
    image: disk-exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: disk-info
#    ports:
#      - "9000:9000"
    volumes:
      - /:/host:ro
    networks:
      - wx
networks:
  wx:
    external: true